"""create users and tasks tables

Revision ID: cecf53d1af26
Revises: 
Create Date: 2026-04-27 19:44:01.765146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cecf53d1af26'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('tasks', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=200),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=200),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.alter_column('tasks', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('tasks', 'title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    # ### end Alembic commands ###
