"""add role column to users

Revision ID: d32ad09fa505
Revises: cecf53d1af26
Create Date: 2026-04-30 14:44:18.791044

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d32ad09fa505"
down_revision: Union[str, Sequence[str], None] = "cecf53d1af26"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


userrole_enum = sa.Enum("admin", "user", name="userrole")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    userrole_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "users",
        sa.Column(
            "role",
            userrole_enum,
            nullable=True,
            server_default="user",
        ),
    )
    op.execute("UPDATE users SET role = 'user' WHERE role IS NULL")
    op.alter_column("users", "role", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    userrole_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
